
// export const Questions = [
//     {
//         id: 1,
//         question: "Why did the math book look sad?",
//         answer: "Because it had too many problems.",
//         level: "easy",
//         theme: "funny",
//     },
//     {
//         id: 2,
//         question: "What has hands but can’t clap?",
//         answer: "A clock.",
//     },
//     {
//         id: 3,
//         question: "I’m tall when I’m young and short when I’m old. What am I?",
//         answer: "A candle.",
//     },
//     {
//         id: 4,
//         question: "What has a head, a tail, is brown, and has no legs?",
//         answer: "A penny.",
//     },
//     {
//         id: 5,
//         question: "Why don’t scientists trust atoms?",
//         answer: "Because they make up everything!",

//     },
//     {
//         id: 6,
//         question: "What do you call a belt made of watches?",
//         answer: "A waist of time!",
//     },
//     {
//         id: 7,
//         question: "Why was the computer cold?",
//         answer: "Because it left its Windows open!",
//     },
//     {
//         id: 8,
//         question: "What kind of tree fits in your hand?",
//         answer: "A palm tree.",
//     },
//     {
//         id: 9,
//         question: "Why did the computer go to the doctor?",
//         answer: "Because it had a virus!",
//     },
//     {
//         id: 10,
//         question: "What gets wetter the more it dries?",
//         answer: "A towel."
//     },
//     {
//     id: 11,
//     question: "What do you call fake spaghetti?",
//     answer: "An impasta!",
//   },
//   {
//     id: 12,
//     question:"How does the ocean say hi?",
//   answer: "It waves!",
//   },
//   {
//     id: 13,
//     question: "Why don’t skeletons fight each other?",
//     answer: "They don’t have the guts.",
//   },
//   {
//     id: 14,
//     question:  "What room doesn’t have doors or windows?",
//   answer: "A mushroom.",

//   },
//   {
//     id: 15,
//     question: "Why did the scarecrow win an award?",
//     answer: "Because he was outstanding in his field!",
//   },
//   {
//     id: 16,
//     question: "What do you call cheese that isn’t yours?",
//     answer: "Nacho cheese!",
//   },
//   {
//     id: 17,
//     question: "Why can’t your nose be 12 inches long?",
//     answer: "Because then it would be a foot.",
//   },
//   {
//     id: 18,
//     question:  "What goes up but never comes down?",
//   answer: "Your age.",
//   },
//   {
//     id: 19,
//     question: "Why don’t eggs tell jokes?",
//     answer: "They’d crack each other up.",
//   },
//   {
//     id: 20,
//     question: "What has a face and two hands but no arms or legs?",
//     answer: "A clock.",
//   }
// ];
export const Questions = [
  {
    id: 1,
    question: "Why did the math book look sad?",
    answer: "Because it had too many problems.",
    level: "easy",
    theme: "funny",
  },
  {
    id: 2,
    question: "What has hands but can’t clap?",
    answer: "A clock.",
    level: "easy",
    theme: "object",
  },
  {
    id: 3,
    question: "I’m tall when I’m young and short when I’m old. What am I?",
    answer: "A candle.",
    level: "medium",
    theme: "riddle",
  },
  {
    id: 4,
    question: "What has a head, a tail, is brown, and has no legs?",
    answer: "A penny.",
    level: "medium",
    theme: "object",
  },
  {
    id: 5,
    question: "Why don’t scientists trust atoms?",
    answer: "Because they make up everything!",
    level: "easy",
    theme: "tech",
  },
  {
    id: 6,
    question: "What do you call a belt made of watches?",
    answer: "A waist of time!",
    level: "easy",
    theme: "wordplay",
  },
  {
    id: 7,
    question: "Why was the computer cold?",
    answer: "Because it left its Windows open!",
    level: "easy",
    theme: "tech",
  },
  {
    id: 8,
    question: "What kind of tree fits in your hand?",
    answer: "A palm tree.",
    level: "medium",
    theme: "nature",
  },
  {
    id: 9,
    question: "Why did the computer go to the doctor?",
    answer: "Because it had a virus!",
    level: "easy",
    theme: "tech",
  },
  {
    id: 10,
    question: "What gets wetter the more it dries?",
    answer: "A towel.",
    level: "medium",
    theme: "riddle",
  },
  {
    id: 11,
    question: "What do you call fake spaghetti?",
    answer: "An impasta!",
    level: "easy",
    theme: "food",
  },
  {
    id: 12,
    question: "How does the ocean say hi?",
    answer: "It waves!",
    level: "easy",
    theme: "nature",
  },
  {
    id: 13,
    question: "Why don’t skeletons fight each other?",
    answer: "They don’t have the guts.",
    level: "easy",
    theme: "spooky",
  },
  {
    id: 14,
    question: "What room doesn’t have doors or windows?",
    answer: "A mushroom.",
    level: "medium",
    theme: "wordplay",
  },
  {
    id: 15,
    question: "Why did the scarecrow win an award?",
    answer: "Because he was outstanding in his field!",
    level: "easy",
    theme: "funny",
  },
  {
    id: 16,
    question: "What do you call cheese that isn’t yours?",
    answer: "Nacho cheese!",
    level: "easy",
    theme: "food",
  },
  {
    id: 17,
    question: "Why can’t your nose be 12 inches long?",
    answer: "Because then it would be a foot.",
    level: "easy",
    theme: "body",
  },
  {
    id: 18,
    question: "What goes up but never comes down?",
    answer: "Your age.",
    level: "medium",
    theme: "life",
  },
  {
    id: 19,
    question: "Why don’t eggs tell jokes?",
    answer: "They’d crack each other up.",
    level: "easy",
    theme: "food",
  },
  {
    id: 20,
    question: "What has a face and two hands but no arms or legs?",
    answer: "A clock.",
    level: "easy",
    theme: "object",
    },
  {
    id: 21,
    question: "I have no lungs, but I need air. I’m not alive, but I grow hair. I make no sound, but I roar and stare. What am I?",
    answer: "A lion statue.",
    level: "hard",
    theme: "animal",
  },
  {
    id: 22,
    question: "I carry my house on my back. I'm slow but always on track. What am I?",
    answer: "A snail.",
    level: "hard",
    theme: "animal",
  },
  {
    id: 23,
    question: "I’m known for my laugh but not for a joke. I live in packs and I'm no bloke. What am I?",
    answer: "A hyena.",
    level: "hard",
    theme: "animal",
  },
  {
    id: 24,
    question: "I live in the cloud but I'm not a bird. I store your secrets without a word. What am I?",
    answer: "A server or cloud storage.",
    level: "hard",
    theme: "tech",
  },
  {
    id: 25,
    question: "I run without legs, I compute without brain. I do what you say, again and again. What am I?",
    answer: "A computer program.",
    level: "hard",
    theme: "tech",
  },
  {
    id: 26,
    question: "I contain bugs, yet I’m not alive. I speak many languages but never talk. What am I?",
    answer: "A codebase.",
    level: "hard",
    theme: "tech",
  },
  {
    id: 27,
    question: "The more you take from me, the bigger I get. What am I?",
    answer: "A hole.",
    level: "hard",
    theme: "general",
  },
  {
    id: 28,
    question: "I am always in front of you but can’t be seen. What am I?",
    answer: "The future.",
    level: "hard",
    theme: "general",
  },
  {
    id: 29,
    question: "The person who makes it, sells it. The person who buys it never uses it. The person who uses it never knows they’re using it. What is it?",
    answer: "A coffin.",
    level: "hard",
    theme: "general",
  },
  {
    id: 30,
    question: "You measure my life in hours and I serve you by expiring. I’m quick when I'm thin and slow when I’m fat. What am I?",
    answer: "A candle.",
    level: "hard",
    theme: "general",
  }

];

